FROM node:18-alpine

WORKDIR /app

# Set environment variables
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV PATH /app/node_modules/.bin:$PATH

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the port Next.js runs on
EXPOSE 3000

# Command to run the app in development mode
CMD ["npm", "run", "dev"]